-- Part 1, Task 2: Verification queries
-- Run against bigbasket_capstone.db (generated by generate_data.py, seed=42)
--
-- ACTUAL OUTPUT (captured after running generate_data.py exactly as specified):
--   products         -> 31
--   customers        -> 50
--   orders           -> 500
--   category_targets -> 6
--
--   orders.status GROUP BY count:
--     Delivered  -> 434
--     Cancelled  -> 42
--     Pending    -> 24
--
-- These match the brief's expected counts exactly, confirming random.seed(42)
-- was left untouched and the script was run as-is.

SELECT COUNT(*) AS total_products FROM products;
SELECT COUNT(*) AS total_customers FROM customers;
SELECT COUNT(*) AS total_orders FROM orders;
SELECT COUNT(*) AS total_category_targets FROM category_targets;

SELECT status, COUNT(*) AS status_count
FROM orders
GROUP BY status
ORDER BY status_count DESC;
